name: Junjie Wang
author: Junjie Wang
markdown: redcarpet
pygments: true
description: I'm an graduate student from University of Washington, Seattle.
greeting_title: Hi, I'm Juunjie.
greeting_text: I'm an engineer from Seattle. This is my homepage.
github: http://github.com/junjiewang
weibo: http://weibo.com/wongism
facebook: http://www.facebook.com/junjie.wang.aaron
renren: http://www.renren.com/256549543
linkedin: http://www.linkedin.com/in/junjiewang
email: junjie@uw.edu
location: +47°40'7.9602"   -122°17'57.7212"
disqus: wjjruc

##Make sure to edit the above fields, especially for disqus. 

